<?php
$col = 8;

if(!isset($size)) $size = null;
if($size == 'tiny') $col = 2;
if($size == 'small') $col = 4;
if($size == 'medium') $col = 6;
if($size == 'large') $col = 8;

?>

<div class="form-group">
    <div class="row">
        <label class="col-md-4 control-label" for="<?php echo $element['day']->getName(); ?>">
            <?php echo $element['day']->getLabel(); ?>
        </label>

        <div class="col-md-<?php echo $col; ?>">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <?php echo $this->formElement($element['day']); ?>
                </div>

                <div class="col-md-4 col-sm-4">
                    <?php echo $this->formElement($element['month']); ?>
                </div>

                <div class="col-md-4 col-sm-4">
                    <?php echo $this->formElement($element['year']); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-4">
            <?php
            echo $this->formElementErrors($element['day']);
            echo $this->formElementErrors($element['month']);
            echo $this->formElementErrors($element['year']);
            ?>
        </div>
    </div>

    <?php
    if(isset($helptext)) {
        ?>
        <div class="row">
            <div class="col-md-offset-4 col-md-<?php echo $col; ?>">
                <span class="help-block"><?php echo $helptext; ?></span>
            </div>
        </div>
    <?php
    }
    ?>
</div>