<br/>
<div class="form-group">
    <label class="col-md-4 control-label" for="<?php echo $element->getName(); ?>">
        <input type="hidden" name="MAX_FILE_SIZE" value="1000000" />
        <?php echo $element->getLabel(); ?>
    </label>
    <div class="controls col-md-8">
        <?php echo $this->formElement($element); ?>
    </div>
    <?php echo $this->formElementErrors($element); ?>
</div>