<?php
$col = 8;

if(!isset($size)) $size = null;
if($size == 'tiny') $col = 2;
if($size == 'small') $col = 4;
?>

<div class="form-group">
    <div class="row">
        <label class="col-md-4 control-label" for="<?php echo $element->getName(); ?>">
            <?php echo $element->getLabel(); ?>
        </label>

        <div class="col-md-<?php echo $col; ?>">
            <?php echo $this->formElement($element); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-4">
            <?php echo $this->formElementErrors($element); ?>
        </div>
    </div>

    <?php
    if(isset($helptext)) {
        ?>
        <div class="row">
            <div class="col-md-offset-4 col-md-<?php echo $col; ?>">
                <span class="help-block"><?php echo $helptext; ?></span>
            </div>
        </div>
    <?php
    }
    ?>
</div>
